
version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "5003:80"
    container_name: caland-app
    volumes:
      - ./src:/usr/share/nginx/html:ro
    restart: unless-stopped
